spring:
  application:
    name: test-task-konus
  datasource:
    url: jdbc:postgresql://postgresql:5432/library
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080