spring:
  application:
    name: test-task-konus
  datasource:
    url: jdbc:postgresql://localhost:5435/library
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true



server:
  port: 8080